### PR TITLE
Review

### PR DESCRIPTION
**Pull request by coderbyheart**
Please look at the individual commits for more details. Especially look for `FIXME` additions.

Please also apply the changes from 61b1c8b601e910a8c03d7d0b1e2b18c87118451a and other commits that would apply to https://github.com/MLopezJ/coiote-to-LwM2M-asset-tracker-v2 before I do a review there.

Most notable changes are: 7f03ff3da6b6e4b4a92acd6497c8485d47684624 and 2cabf4d4de15b3a8832060f943baacef2018c3f4

### CODE REVIEW

**Comment by MLopezJ** [comment]
@coderbyheart , with https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/de63b793fc79966d29d1bece99da33564d0de80a  you mean convert all tests of the proyect to `node:test` or just the main converter test?

**Comment by coderbyheart** [comment]
Fully remove jest from the project

**Comment by MLopezJ** [comment]
- [x] rename project https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/faf9f508a0c44c9e07b474fd664a915e033d0704
- [x] convert `notes` to `ADR` https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/e72ad32c5d75b02074b304683e8c4f534332d905
- [x] Remove references to personal repo https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/e72ad32c5d75b02074b304683e8c4f534332d905 & https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/faf9f508a0c44c9e07b474fd664a915e033d0704
- [x] release to NPM https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/987ca620eea26256c8277b71da8b60b36c105426
- [x] Update readme https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/987ca620eea26256c8277b71da8b60b36c105426
- [x] update package.json https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/f7b9eb8c5921cb025ed3eb657d9a086e2e989531
- [x] update package.json : keywords should be slugs https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/fde3ce6598711908c9b3241d7df67514cc3c9c99
- [x] use correct license: https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/61b1c8b601e910a8c03d7d0b1e2b18c87118451a
- [x] Analyze real use of end-to-end tests https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/4c70abe60625eedbecb9159378bdb9ecbcbabbf0 
- [x] improve example https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/45df0fb16551b9f4d32dceccdcba76c1aae1cc2f
- [x] Return error: https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/a6f0ee2ef3fb8113227366a95d1a312b28119248
- [x] Update output format https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/f27d2dd2405fc51ec83a4a366305fb9509527075
- [x] update comments https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/1c3a0108492d9d5041f0138500625cc8e5a8566a 
- [x] remove functions https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/ae6be38a56d0a67a05960343f58821b654f5cf05 
- [x] Analyze advantage of https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/2cabf4d4de15b3a8832060f943baacef2018c3f4 
- [x] Identify missing values https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/7f03ff3da6b6e4b4a92acd6497c8485d47684624
- [x] use `node:test` https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/de63b793fc79966d29d1bece99da33564d0de80a 





## continuation

* A meeting with Simen was set to Thursday 07/09/2023 at 10 for solve `Identify missing values` https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/7f03ff3da6b6e4b4a92acd6497c8485d47684624
* TODOs are added to change links after a new repo link is given. This is just to not break links. This is also related to `Remove references to personal repo` https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/e72ad32c5d75b02074b304683e8c4f534332d905 & https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/faf9f508a0c44c9e07b474fd664a915e033d0704
* Package was tested in NPM and a new repo in the Nordic Semiconductor GitHub account was requested to IT. This is related to `release to NPM` https://github.com/MLopezJ/LwM2M-Asset-Tracker-V2-to-Asset-Tracker-web-app/pull/1/commits/987ca620eea26256c8277b71da8b60b36c105426

**Comment by MLopezJ** [comment]
Thanks for the review @coderbyheart . All the recommendations were analyzed and implemented. 

In https://github.com/MLopezJ/asset-tracker-lwm2m-js/pull/5 is the current status of the project, with the open questions and pending tasks. I am working on that with Pisut.

I will let you know if I need your help there.

**Pull request closed without merging**
